# Minimal Search Configuration - Just SKULOC with EcommATS view

datasets:
  SKULOC:
    baseTable: skuloc
    
    columns:
      sku_id: 
        sql: "sku_id"
        type: long
        alias: "skuId"
      location_number: 
        sql: "location_number"
        type: int
        alias: "locationNumber"
      available_qty: 
        sql: "available_qty"
        type: long
        alias: "availableQty"
      ecomm_pick_reserve: 
        sql: "ecomm_pick_reserve"
        type: long
        alias: "ecommPickReserve"
      ecomm_pack_reserve: 
        sql: "ecomm_pack_reserve"
        type: long
        alias: "ecommPackReserve"
    
    filters:
      locationNumberIn:
        column: "location_number"
        type: "int[]"
        op: "IN"
        max: 5000
    
    computed:
      ats: "GREATEST(available_qty - (ecomm_pick_reserve + ecomm_pack_reserve), 0)"
    
    pagination:
      keysetColumns: ["sku_id", "location_number"]
      defaultPageSize: 50
      maxPageSize: 500
      maxUnpaginatedRows: 10000
    
    defaultSort:
      - field: "sku_id"
        direction: "ASC"
      - field: "location_number"
        direction: "ASC"
    
    views:
      EcommATS:
        name: "EcommATS"
        description: "E-commerce available to sell view"
        columns: 
          - "sku_id"
          - "location_number"
          - "available_qty"
          - "ecomm_pick_reserve"
          - "ecomm_pack_reserve"
        computed:
          - "ats"
        filters:
          - "locationNumberIn"
        defaultPageSize: 50